version: '3.9'

services:
  db:
    build: database/
    ports:
      - '5432:5432'
  api1:
    build: .
    ports:
      - '3001:8080'
  api2:
    build: .
    ports:
      - '3002:8080'
  api3:
    build: .
    ports:
      - '3003:8080'
  nginx:
    build: nginx/
    ports:
      - '8080:80'
    depends_on:
      - api1
      - api2
      - api3
